// <auto-generated />
using System;
using FormatChanger.ContextData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FormatChanger.Migrations
{
    [DbContext(typeof(ContextSets))]
    [Migration("20210726225536_MappedFields")]
    partial class MappedFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("FormatChanger.Model.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FatherId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<char?>("PaddingChar")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringFormatter")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("FormatChanger.Model.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("FormatChanger.Model.FormatMappedField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FatherId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FieldFromId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FieldToId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.HasIndex("FieldFromId");

                    b.HasIndex("FieldToId");

                    b.ToTable("FormatMappedField");
                });

            modelBuilder.Entity("FormatChanger.Model.FormatMapper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormatFromId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormatToId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormatFromId");

                    b.HasIndex("FormatToId");

                    b.ToTable("FormatMapper");
                });

            modelBuilder.Entity("FormatChanger.Model.Field", b =>
                {
                    b.HasOne("FormatChanger.Model.Format", "Father")
                        .WithMany("Fields")
                        .HasForeignKey("FatherId");

                    b.Navigation("Father");
                });

            modelBuilder.Entity("FormatChanger.Model.FormatMappedField", b =>
                {
                    b.HasOne("FormatChanger.Model.FormatMapper", "Father")
                        .WithMany("MyProperty")
                        .HasForeignKey("FatherId");

                    b.HasOne("FormatChanger.Model.Field", "FieldFrom")
                        .WithMany()
                        .HasForeignKey("FieldFromId");

                    b.HasOne("FormatChanger.Model.Field", "FieldTo")
                        .WithMany()
                        .HasForeignKey("FieldToId");

                    b.Navigation("Father");

                    b.Navigation("FieldFrom");

                    b.Navigation("FieldTo");
                });

            modelBuilder.Entity("FormatChanger.Model.FormatMapper", b =>
                {
                    b.HasOne("FormatChanger.Model.Format", "FormatFrom")
                        .WithMany()
                        .HasForeignKey("FormatFromId");

                    b.HasOne("FormatChanger.Model.Format", "FormatTo")
                        .WithMany()
                        .HasForeignKey("FormatToId");

                    b.Navigation("FormatFrom");

                    b.Navigation("FormatTo");
                });

            modelBuilder.Entity("FormatChanger.Model.Format", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("FormatChanger.Model.FormatMapper", b =>
                {
                    b.Navigation("MyProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
